### ISSUE TITLE
How to use the "Win" Key instead of Caps Lock

### ISSUE THREAD

**Issue by tuxflo** [Noneus/US-Keyboard-Layout-with-German-Umlauts#2]
Hi!
I'm trying to get the Umlaute to work on an US Keyboard but I can not use Caps Lock because I mapped it already to "Esc" (vim user). Is there a way to use the "Win" key instead  of Caps Lock?

Thanks in advance,
Flo

**Comment by slohmaier** [comment]
What operating system are u using?

**Comment by tuxflo** [comment]
KDE Neon, which is based on Ubuntu 16.04.

⁣Sent from Blue ​

**Comment by lukeb2e** [comment]
If you are still trying to get this to work you can use the X11 config from my pull request and replace
`include "level3(caps_switch)"` with `include "level3(win_switch)"`.

For more options you can check in `/usr/share/X11/xkb/symbols/level3`.

**Comment by tuxflo** [comment]
Hi, thanks for the reply but meanwhile I found out, that X11 has this feature out of the box and it could easily be enabled via in the advanced keyboard config menu.
